on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: mike5535/db
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 3306:3306
    steps:
    - uses: actions/checkout@v2
    - run: cmake interface_bd/
    - run: make
    - run: docker-compose up -d db
    - name: Sleep for 120 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '120s'
    - run: ./tests
